services:
  app:
    image: node:22
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development

volumes:
  node_modules:
